apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: compute.datumapis.com-workload
spec:
  serviceRef:
    name: "compute.datumapis.com"
  kind: Workload
  plural: workloads
  singular: workload
  permissions:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - watch
  subresources:
    - name: status
      permissions:
        - get
        - update
        - patch
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
