apiVersion: v1
kind: ConfigMap
metadata:
  name: compute-prometheus-adapter-config
  namespace: compute-system
  labels:
    app.kubernetes.io/name: compute-prometheus-adapter
    app.kubernetes.io/part-of: compute
data:
  config.yaml: |
    resourceRules:
      cpu:
        containerQuery: |
          sum by (<<.GroupBy>>) (
            rate(datum_compute_instance_cpu_usage_seconds_total{<<.LabelMatchers>>,container!=""}[2m])
          )
        nodeQuery: |
          sum by (<<.GroupBy>>) (
            rate(datum_compute_instance_cpu_usage_seconds_total{<<.LabelMatchers>>}[2m])
          )
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
            node:
              resource: node
        containerLabel: container
      memory:
        containerQuery: |
          sum by (<<.GroupBy>>) (
            datum_compute_instance_memory_working_set_bytes{<<.LabelMatchers>>,container!=""}
          )
        nodeQuery: |
          sum by (<<.GroupBy>>) (
            datum_compute_instance_memory_working_set_bytes{<<.LabelMatchers>>}
          )
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
            node:
              resource: node
        containerLabel: container
      window: 2m
