apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - service_account.yaml
  - rbac.yaml
  - serving-cert.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - apiservice.yaml
