apiVersion: v1
kind: Service
metadata:
  name: compute-prometheus-adapter
  namespace: compute-system
  labels:
    app.kubernetes.io/name: compute-prometheus-adapter
    app.kubernetes.io/part-of: compute
spec:
  selector:
    app.kubernetes.io/name: compute-prometheus-adapter
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
