apiVersion: v1
kind: ServiceAccount
metadata:
  name: compute-prometheus-adapter
  namespace: compute-system
  labels:
    app.kubernetes.io/name: compute-prometheus-adapter
    app.kubernetes.io/part-of: compute
