apiVersion: quota.miloapis.com/v1alpha1
kind: GrantCreationPolicy
metadata:
  name: compute-default-quota
spec:
  trigger:
    resource:
      apiVersion: resourcemanager.miloapis.com/v1alpha1
      kind: Project
  target:
    resourceGrantTemplate:
      metadata:
        generateName: compute-quota-
        namespace: "{{trigger.metadata.namespace}}"
      spec:
        consumerRef:
          apiGroup: resourcemanager.miloapis.com
          kind: Project
          name: "{{trigger.metadata.name}}"
        allowances:
          - resourceType: compute.datumapis.com/instances
            buckets:
              - amount: 10
          - resourceType: compute.datumapis.com/vcpus
            buckets:
              - amount: 40000
          - resourceType: compute.datumapis.com/memory
            buckets:
              - amount: 81920
