apiVersion: services.miloapis.com/v1alpha1
kind: Service
metadata:
  name: compute
spec:
  description: |
    Low-latency virtual machine workloads with CPU and memory resources billed by consumption.
  displayName: Compute
  owner:
    producerProjectRef:
      name: datum-cloud
  phase: Published
  serviceName: compute.datumapis.com
