apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../crd/bases/compute.datumapis.com_instances.yaml
  - ../crd/bases/compute.datumapis.com_workloaddeployments.yaml
  - ../crd/bases/compute.datumapis.com_workloads.yaml

components:
  - ../../components/federation
