apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/crd
  - ../../base/manager
  - ../../base/webhook
  - ../../base/certmanager
components:
  - ../../components/leader_election
  - ../../components/controller_rbac
