apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-manager
spec:
  template:
    spec:
      volumes:
        - name: webhook-server-tls
          csi:
            driver: csi.cert-manager.io
            volumeAttributes:
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/issuer-name: datum-control-plane
