apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: UPSTREAM_KUBECONFIG
              value: /etc/kubernetes/downstream/auth/downstream-kubeconfig.yaml
          volumeMounts:
            - name: downstream-kubeconfig
              mountPath: /etc/kubernetes/downstream/auth
              readOnly: true
            - name: karmada-token
              mountPath: /etc/kubernetes/karmada-token
              readOnly: true
      volumes:
        - name: downstream-kubeconfig
          configMap:
            name: compute-downstream-kubeconfig
        - name: karmada-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: https://karmada-apiserver.karmada-system.svc.cluster.local:5443
                  path: token
